config/routes.rb
Todo::Application.routes.draw do
  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'
  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    #if params[:query].present?
      #@user = User.search(params[:query], page: params[:page])
    #else
      #@user = User.all.page params[:page]
    #end
  end

  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user 
  		@todo_lists = @user.todo_lists.all
  		render action: :show
  	else
  	render file: 'public/404', status: 404, formats: [:html]
  end

  def create
    @user = User.create( user_params )
  end
end

private
  
  def user_params
    params.require(:user).permit(:avatar)
  end
 
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<h1><%= @user.profile_name %></h1>

<h4><%= link_to "Edit User", edit_user_registration_path %></h4>

<% if signed_in? %>
   
<div id="friend-status">
	<% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
	<%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: 'btn btn-default' %> 
	<% else %>
	<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn btn-default', id: 'add-friendship', data: { friend_id: @user.to_param }%>
	<% end %>
</div>
<% end %>


<% if @todo_lists %>
	<% @todo_lists.each do |todo_list| %>
	<div class="todo_list" id="<%= dom_id(todo_list) %>">
	  <h2><%= todo_list.title %></h2>
	  <p><%= todo_list.description %></p>
	  <ul class="functions">
	    <li><%= link_to "List Items", todo_list_todo_items_path(todo_list) %></li>
	    <li><%= link_to 'Show', todo_list %></li>
	    <li><%= link_to 'Edit', edit_todo_list_path(todo_list) %></li>
	    <li><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	  </ul>
	  <br class="clear" />
	</div>
		<% end %>
		<% end %>