config/routes.rb
Todo::Application.routes.draw do
  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'
  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :todo_list

  validates :content, presence: true,
  					  length: { minimum: 2 }
  scope :complete, -> { where("completed_at is not null")}
  scope :incomplete, -> { where(completed_at: nil)}

  def completed?
  	!completed_at.blank?  	
  end  		
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_todo_list


  def index
    
  	
  end

  def new  	
  	@todo_item = @todo_list.todo_items.new  	
  end

  def create  
  	@todo_item = @todo_list.todo_items.new(todo_item_params)
    @todo_item.user_id = current_user.id
  	if @todo_item.save
  		flash[:success] = "Added todo list item."
  		redirect_to todo_list_todo_items_path
  	else
  		flash[:error] = "There was a problem adding that todo list item."
  		render action: :new
  	end
  end

  def edit    
    @todo_item = @todo_list.todo_items.find(params[:id])    
  end

  def update    
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Todo list item could not be deleted."
    end
    redirect_to todo_list_todo_items_path    
  end

  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to todo_list_todo_items_path, notice: "Todo item marked as complete"    
  end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)    
  end

  private
  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
    
  end

  def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end


  def todo_item_params
  	params[:todo_item].permit(:content, :difficult)  	
  end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>      
      </ul>
    </div>



  <%= form.label :content %>
  <%= form.text_field :content %>

  <%= form.label :difficulty %>
  <%= form.select :difficult, options_for_select([["Easy", "Easy"], ["Intermediate", "Intermediate"], ["Difficult", "Difficult"]], @todo_item.difficult) %>

  <%= form.submit "Save" %>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %> - Editing Todo List Item</h1>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>    
<% end %>

app/views/todo_items/index.html.erb
<h1><%= @todo_list.title %></h1>

<table class="todo_items">
  <table class="todo_items">
  <thead>
    <tr>
      <th width="25%">Completed?</th>
      <th width="35%">Content</th>
      <th width="10%">Difficulty</th>
      <th width="20%">Name</th>
      <th width="10%">Functions</th>
    </tr>
  </thead>
  <tbody>
  <% @todo_list.todo_items.each do |todo_item| %>
  <tr id="<%= dom_id(todo_item) %>">
    <td>
      <% if todo_item.completed? %>
        <%= todo_item.completed_at %>
      <% else %>
        <%= link_to "Mark Complete", complete_todo_list_todo_item_path(todo_item), method: :patch %>
      <% end %>
    </td>
    <td><%= todo_item.content %></td>
    <td><%= todo_item.difficult %></td>
    <td><%= link_to todo_item.user.full_name, profile_path(todo_item.user) %></td>
    <td>
      <%= link_to "Edit", edit_todo_list_todo_item_path(todo_item) %>
      <%= link_to "Delete", todo_list_todo_item_path(todo_item), method: :delete, data: { confirm: "Are you sure?" } %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= link_to "New Todo Item", new_todo_list_todo_item_path %>
</p>

<%= current_user.points %>
<ul>
<% current_user.badges.each do |badge| %>
  <li><%= badge.name %></li>
<% end %>
</ul>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.title %> - Add Todo List Item</h1>
<%= form_for [@user, @todo_list, @todo_item] do |form| %>
  <%= render partial: form %>    
<% end %>