config/routes.rb
Todo::Application.routes.draw do
  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'
  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="navbar-header">
			<div class="container">
		
		<ul class="nav nav-pills">
			<li class="active"><%= link_to "Home", root_path %></li>
			<li><%= link_to "Todo lists", todo_lists_path %></li>
		
		<% if user_signed_in? %>
		<li class="nav pull-right">
			<%= form_tag profiles_show_path, class: "form", method: :get do %>
					    <%= text_field_tag :query, params[:query], class: "form-control" %>
					    </li>
					    <li class="nav pull-right">
					    <%= submit_tag "Search", class: "btn btn-primary" %>
					    <% if params[:query].present? %>
							<%= link_to "clear", profiles_show_path %>
						<% end %>
						</li>
			<% end %>
		
		
    	 
		
			<li class="nav pull-right"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
		
		
			<li class="nav pull-right"><%= link_to current_user.full_name, profiles_show_path(id: current_user.profile_name) %></li>
		
		
			<li class="nav pull-right"><%= link_to "Friends", user_friendships_path %></li>
		
		<% else %>
		
			<li class="nav pull-right"><%= link_to "Sign In", new_user_session_path %></li>
		
		
			<li class="nav pull-right"><%= link_to "Sign up", new_user_registration_path %></li>
		
		<% end %>
	</ul>
		
		<br class="clear" />
	</div>
	</div>
</nav>

<div class="container">
    <% flash.each do |type, message| %>

    <div class="alert <%= type %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
      <%= message %>
    <% end %>
</div>
</div>
<div class="container">
  <%= yield %>
</div>

</body>
</html>